USE biblioteca;

CREATE TABLE sync_shopping_lists (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sync_shopping_items (
    id INT PRIMARY KEY,
    description TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    list_id INT,
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sync_hospital_citas (
    id INT PRIMARY KEY,
    paciente VARCHAR(255) NOT NULL,
    descripcion TEXT,
    fecha VARCHAR(50),
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);